### ISSUE TITLE
Undo rename main to master

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/cookiecutter-mda#1]
As we are just starting work on this cookiecutter, I thought I'd start off by renaming the master branch to main. I think this falls in line with the general opinions expressed in https://github.com/MDAnalysis/mdanalysis/issues/3542 and in meetings. This issue has been opened to gather discussion if people disagree with this decision. I'll close it in a week if no one has objections.

**Comment by orbeckst** [comment]
Using *main* instead of *master* from the start is a good idea, I am 💯 in favor 👍 .
